############################################################
# Dockerfile to build the Meteor microservice container image
# Based on jshimko/meteor-launchpad
############################################################

# Set the base image to meteor-launchpad
FROM jshimko/meteor-launchpad:devbuild

# File Author / Maintainer
MAINTAINER C2G Consulting